# Generated by Django 4.2 on 2024-03-11 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Rodziny'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Członkowie Rodzin'},
        ),
        migrations.AlterField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(blank=True, to='main.member'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('comment', models.CharField(max_length=1024)),
                ('member_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions_from_me', to='main.member')),
                ('member_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions_about_me', to='main.member')),
            ],
        ),
    ]
