# Generated by Django 4.2 on 2024-03-19 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_assessment_options_assessment_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_boss',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriprion', models.CharField(max_length=2048)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'In Progress'), (3, 'Completed')], db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_wishes', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_on'],
            },
        ),
    ]
