# Generated by Django 4.2 on 2024-03-23 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_remove_wish_owner_member_is_favourite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='owner_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_wishes', to='main.member'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_wishes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wish',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_gifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
