# Generated by Django 4.2 on 2024-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_wish_owner_member_alter_wish_owner_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Utworzone'), (2, 'Realizowane'), (3, 'Zakończone'), (4, 'Usunięte')], db_index=True, default=1),
        ),
    ]
